apiVersion: v1
kind: Secret
metadata:
  name: test-framework-secrets
  namespace: fintech-qa
type: Opaque
stringData:
  DB_USERNAME: "fintech_user"
  DB_PASSWORD: "fintech_pass"
  INFLUXDB_TOKEN: "fintech-super-secret-token"
